name: Releases

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: yarn install --frozen-lockfile
    - run: yarn pack --filename=mdl-ts.tgz
    - uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        tag_prefix: "v"
    - name: Create Release
      if: steps.update_tag.outputs.tagname
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.update_tag.outputs.tagname }}
        release_name: Release ${{ steps.update_tag.outputs.tagname }}
